name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test -- --coverage

    - name: Generate coverage badge
      run: npm run test:coverage

    - name: Upload coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: coverage/badge.svg
